XSVC/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required as auth
# import autocomplete_light
# # import every app/autocomplete_light_registry.py
# autocomplete_light.autodiscover()
from Xarxa.views import AportacioxTagListView, LinkFormView
from Xarxa.views import DebatListView, EscritoriListView, ResumListView, AportacioListView, AportacioCreateView, VoteFormView, AportacioxTemaListView
from Xarxa.views import AportacioDetailView, UserProfileDetailView, UserProfileEditView, AportacioUpdateView, VotedebatFormView, ResumxTemaListView
from Xarxa.views import DebatCreateView, DebatDetailView, DebatUpdateView, ResumCreateView, ResumDetailView, ResumUpdateView, UserProfileDeleteView
# Uncomment the next two lines to enable the admin:
import notification
from notification import urls
from Xarxa.forms import UserRegForm
import regbackend
from registration.backends.default.views import RegistrationView
import postman
import micawber




from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'XSVC.views.home', name='home'),
    # url(r'^XSVC/', include('XSVC.foo.urls')),
    url(r'^$', EscritoriListView.as_view() ,name='escritori'),
    url(r'^aportacions/(?P<pk>\d+)/debats/$', DebatListView.as_view() ,name="debats"),
    url(r"^login/$", "django.contrib.auth.views.login",
        {"template_name": "login.html"}, name="login"),
    url(r"^logout/$", "django.contrib.auth.views.logout_then_login",
        name="logout"),
    url(r'^aportacions/$', AportacioListView.as_view() ,name='aportacions'),
    url(r'^aportacions/create/$', AportacioCreateView.as_view() ,name='aportacio_create'),
    url(r"^aportacions/update/(?P<pk>\d+)/$", auth(AportacioUpdateView.as_view()),
        name="aportacio_update"),
    url(r"^aportacions/(?P<pk>\d+)/$", AportacioDetailView.as_view(),
        name="aportacio_detail"),
    url(r'^aportacions/(?P<pk>\d+)/debats/reply/(?P<id>\d+)/$', DebatCreateView.as_view() ,name='debat_create'),
    # url(r'^aportacions/(?P<pk>\d+)/debats/reply/$', FirstDebatCreateView.as_view() ,name='first_debat_create'),
    url(r"^debat/update/(?P<pk>\d+)/$", auth(DebatUpdateView.as_view()),
        name="debat_update"),
    url(r"^debat/(?P<pk>\d+)/$", DebatDetailView.as_view(),
        name="debat_detail"),
    url(r'^resums/$', ResumListView.as_view() ,name='resums'),
    url(r'^resum/create/$', ResumCreateView.as_view() ,name='resum_create'),
    url(r"^resum/update/(?P<pk>\d+)/$", auth(ResumUpdateView.as_view()),
        name="resum_update"),
    url(r"^resum/(?P<pk>\d+)/$", ResumDetailView.as_view(),
        name="resum_detail"),
    url('^inbox/notifications/', include(notification.urls)),
    url(r'^tema/(?P<pk>\d+)/aportacions/$', AportacioxTemaListView.as_view() ,name='aportacionsxtema'),
    url(r'^tema/(?P<pk>\d+)/resums/$', ResumxTemaListView.as_view() ,name='resumsxtema'),
    url(r'^tag/(?P<slug>\w+)/aportacions/$', AportacioxTagListView.as_view() ,name='aportacionsxtag'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    (r'^messages/', include('postman.urls')),
    # url(r'^note/', include('notification.urls')),
    url(r'^votedebat/$', auth(VotedebatFormView.as_view()), name="votedebat"),
    url(r'^charts/(?P<pk>\d+)/simple.png$', 'Xarxa.views.pygraphviz_graph', name="chart"),
    # url(r'^resums/$', 'Xarxa.views.resums' ,name='resums'),
    # url(r'^aportacions/$', 'Xarxa.views.aportacions' ,name='aportacions'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # url(r"^accounts/", include("registration.backends.simple.urls")),
    url(r"^users/delete/(?P<slug>\w+)/$", auth(UserProfileDeleteView.as_view()), name="registration_delete"),
    url(r'^accounts/register/$', RegistrationView.as_view(),
        {'backend': 'registration.backends.default.DefaultBackend','form_class': UserRegForm}, name='registration_register'),
    url(r"^accounts/", include('registration.backends.default.urls')),
    url(r"^users/(?P<slug>\w+)/$", UserProfileDetailView.as_view(),
        name="profile"),
    url(r"edit_profile/$", auth(UserProfileEditView.as_view()),
        name="edit_profile"),
    url(r'^link/$', LinkFormView.as_view(), name="link"),
    url(r'^url/$', 'Xarxa.views.link_verify'),
    url(r'^vote/$', auth(VoteFormView.as_view()), name="vote"),
#les seguents 4 url's s'utilitzen per a recuperar la conta quan has olvidat la contrasenya
#basat en: http://garmoncheg.blogspot.com.au/2012/07/django-resetting-passwords-with.html
    url(r'^user/password/reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : '/user/password/reset/done/'},
        name="password_reset"),
    (r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'),
    (r'^user/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect' : '/user/password/done/'}),
    (r'^user/password/done/$',
        'django.contrib.auth.views.password_reset_complete'),
)

Xarxa/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse, reverse_lazy
from datetime import datetime
from django.utils.timezone import now
from django.db.models import Count
import notification
from notification import models as notification
from notification.models import send
from notification.models import *
from tagging.fields import TagField
from django_countries.fields import CountryField
from embed_video.fields import EmbedVideoField
from micawber.parsers import extract
from micawber.contrib.mcdjango.providers import bootstrap_basic
# Create your models here.

class Escritori(models.Model):
    titol = models.CharField(max_length="40")

    def __unicode__(self):
        return "%s" % (self.titol)


class Tema(models.Model):
    name = models.CharField(max_length=15)

    def __unicode__(self):
        return "%s" % (self.name)

class Seccio(models.Model):
    name = models.CharField(max_length=15)
    tema = models.ForeignKey('Tema', related_name='seccions')

    def __unicode__(self):
        return "%s" % (self.name)


class DebatVoteCountManager(models.Manager):
    def get_query_set(self):
        return super(DebatVoteCountManager, self).get_query_set().annotate(votes=Count('votedebats')
        )

class Debat(models.Model):
    titol = models.CharField(max_length="60")
    datahora = models.DateTimeField(default=now,blank=True)
    parent = models.ForeignKey('self', related_name='children', blank=True, null= True)
    autor = models.ForeignKey(User)
    text = models.TextField(max_length=500)
    aportacio = models.ForeignKey('Aportacio', related_name='debats')
    rank_score = models.FloatField(default=0.0)

    with_votes = DebatVoteCountManager()
    objects = models.Manager()


    def __unicode__(self):
        return "%s" % (self.titol)

    def get_absolute_url(self):
        return reverse('debats', kwargs={'pk': self.aportacio_id} )


    def as_tree(self):
        children = list(self.children.all())
        branch = bool(children)
        yield branch, self
        for child in children:
            for next in child.as_tree():
                yield next
        yield branch, None

    def set_rank(self):
        # Based on HN ranking algo at http://amix.dk/blog/post/19574
        SECS_IN_HOUR = float(60*60)
        GRAVITY = 1.2

        delta = now() - self.datahora
        item_hour_age = delta.total_seconds() // SECS_IN_HOUR
        votes = self.votes - 1
        self.rank_score = votes / pow((item_hour_age+2), GRAVITY)
        self.save()

#mira el exemple de stealrumors. planteja d'utilitzar django-celery per a refrescar amb frequencia
class LinkVoteCountManager(models.Manager):
    def get_query_set(self):
        return super(LinkVoteCountManager, self).get_query_set().annotate(votes=Count('vote')
        ).order_by('-rank_score', '-votes')

class Link(models.Model):
    url = models.TextField(blank=True, null=True)
    aportacio = models.ForeignKey('Aportacio', related_name='links', null=True, blank=True)

    def __unicode__(self):
        return "%s %s" % (self.url, self.aportacio)

class Aportacio(models.Model):
    titol = models.CharField(max_length="40")
    autor = models.ForeignKey(User)
    datahora = models.DateTimeField(default=now,blank=True, null=True)
    entradilla = models.TextField(max_length="120", blank=True, null=True)
    text = models.TextField()
    rank_score = models.FloatField(default=0.0)
    debat_id = models.CharField(max_length="50", null=True, blank=True)
    tema = models.ForeignKey('Tema', related_name='aportacions', null=True, blank=True)
    seccio = models.ForeignKey('Seccio', related_name='aportacions', null=True, blank=True)
    tags = TagField()
    country = CountryField(null=True, blank=True)
    video = EmbedVideoField(null=True, blank=True)
    # debat = Xarxa.models.Debat()

    with_votes = LinkVoteCountManager()
    objects = models.Manager()


    def __unicode__(self):
        return "%s" % (self.titol)

    def get_absolute_url(self):
        return reverse('aportacions')

    def set_rank(self):
        # Based on HN ranking algo at http://amix.dk/blog/post/19574
        SECS_IN_HOUR = float(60*60)
        GRAVITY = 1.2

        delta = now() - self.datahora
        item_hour_age = delta.total_seconds() // SECS_IN_HOUR
        votes = self.votes - 1
        self.rank_score = votes / pow((item_hour_age+2), GRAVITY)
        self.save()



class Resum(models.Model):
    titol = models.CharField(max_length="40")

    def __unicode__(self):
        return "%s" % (self.titol)

    def get_absolute_url(self):
        return reverse('resums')







class Vote(models.Model):
    voter = models.ForeignKey(User)
    aportacio = models.ForeignKey(Aportacio)

    def __unicode__(self):
        return "%s voted %s" % (self.voter.username, self.aportacio.titol)


class Votedebat(models.Model):
    voter = models.ForeignKey(User)
    debat = models.ForeignKey(Debat, related_name="votedebats")

    def __unicode__(self):
        return "%s voted %s" % (self.voter.username, self.debat.titol)

from django.contrib.auth.models import AbstractUser

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    #basic attributes
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=30)
    birthday = models.DateField()
    job = models.CharField(max_length=30)
    # activity = models.CharField(max_length=30)
    # city = models.CharField(max_length=30)
    # country = models.CharField(max_length=20)
    # bio = models.TextField(null=True)
    # situacion_laboral = models.CharField(max_length=20)
    # web = models.CharField(max_length=30)
    # Extra attributes
    # foto = models.ImageField(null=True, blank=True, upload_to='/static/img')
    # empresa = models.CharField(max_length=25, null=True, blank=True)
    # cargo = models.CharField(max_length=25)
    # telephone = models.IntegerField(max_length=15)
    # public = models.BooleanField()
    # receive_all_alerts = models.BooleanField()



    def __unicode__(self):
        return "%s's profile" % self.user

# def create_profile(sender, instance, created, **kwargs):
#     if created:
#         profile, created = UserProfile.objects.get_or_create(user=instance)

def deb_ap_create(sender, instance, created, **kwargs):
    if created:
        debat, created = Debat.objects.get_or_create(titol = instance.titol, autor = instance.autor,
                                 datahora = instance.datahora, aportacio = instance)
        instance.debat_id = debat.id

#inici del codi per a llistar els enllacos que hi hagi en el text
    p = bootstrap_basic()
    links = extract(instance.text,p)
    lks = Link.objects.filter(aportacio=None).update(aportacio = instance)

    if links[0]:
        for link in links[0]:
                s = Link.objects.get_or_create(url=link, aportacio=instance)


#fi del codi per llistar enllacos

def send_comment_notification(sender, instance, created, **kwargs):
    if created:
        if not instance.aportacio.autor == instance.autor:
            send([instance.aportacio.autor], "comment_to_app", {"debat": instance})

        # notification.send([instance], "comment_to_app")

        debats = Debat.objects.filter(aportacio=instance.aportacio)
        userz = set()
        for item in debats:
            if not item.autor == instance.autor and item.autor not in userz and not item.autor == instance.aportacio.autor:
                userz.add(item.autor)
        # notification.send_now(userz, 'comment_to_com' )
        for user in userz:
            notification.send([user], "comment_to_com", {"debat": instance})






# def send_notification(sender, aportacio, debat, **kwargs):
    # notification.send([aportacio.autor], "comment_to_app", {"debat": debat})

from django.db.models.signals import post_save
# post_save.connect(create_profile, sender=User)
post_save.connect(deb_ap_create, sender=Aportacio) #Crea la instancia debate de cualquier aportacion creada
post_save.connect(send_comment_notification, sender=Debat)


from django_mailbox.signals import message_received
from django.dispatch import receiver

@receiver(message_received)
def message_rec(sender, message, **args):
    print("kghekjwhgekw")
from django.db import models


#si actives les seguentes 5 linees dona error, no hi ha nota solucionada que ho arregli
#tot i aixo hi ha caracteristiques de la app tagging que requereixen aquest registre
# import tagging
#
#
# tagging.register(Aportacio)


#La classe TagSelectMultiple de moment no s'utilitza, pero es com el seleccionador de destinataris del modul de missatges
# de Facebook. En el futur ens pot interesar per el nostre modul de missatges per escollir destinataris

# from django import forms
# from django.forms.util import flatatt
# from django.utils.encoding import force_unicode
# from django.utils.html import escape, conditional_escape
# from django.utils.safestring import mark_safe
#
# class TagSelectMultiple(forms.SelectMultiple):
#     def render(self, name, value, attrs=None, choices=()):
#         if value is None: value = []
#         final_attrs = self.build_attrs(attrs, name=name)
#         self.name = name
#         output = [u'<div class="tagSelector" multiple="multiple"%s>' % flatatt(final_attrs)]
#         options = self.render_options(choices, value)
#         if options:
#             output.append(options)
#         output.append('<input type=text>')
#         output.append('</div>')
#         return mark_safe(u'\n'.join(output))
#
#     def render_option(self, selected_choices, option_value, option_label):
#         if unicode(option_value) in selected_choices:
#             return u'<span class="tag">%s <a>x</a><input name="%s" type="hidden" value="%s"/></span>' % (
#                 conditional_escape(force_unicode(option_label)), escape(self.name), escape(option_value))
#         return ''

Xarxa/templates/Xarxa/aportacio_form.html
{% extends "base.html" %}

{% load micawber_tags %}


{#<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/themes/base/jquery-ui.css"#}
{#      rel=stylesheet type="text/css" xmlns="http://www.w3.org/1999/html">#}
{#    <link href="jquery-tagselector.css" rel=stylesheet>#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>#}
{#    <script src="jquery-tagselector.js"></script>#}

    <script>
    $(function() {

        var tags = [
            { id: 42, toString: function() { return 'jQuery'; } },
            { id: 31, toString: function() { return 'Python'; } },
            { id: 25, toString: function() { return 'HTML'; } },
            { id: 83, toString: function() { return 'PHP'; } },
            { id: 40, toString: function() { return 'ASP.NET MVC'; } },
            { id: 25, toString: function() { return 'CSS'; } },
            { id: 66, toString: function() { return 'JavaScript'; } },
            { id: 87, toString: function() { return 'C#'; } },
            { id: 28, toString: function() { return 'D'; } },
            { id: 91, toString: function() { return 'Java'; } },
            { id: 10, toString: function() { return 'Ruby'; } },
        ];
        $('#tags').tagSelector(tags, 'tags');

    });
    </script>




{% block content %}

{#        <div id=tags class=tagSelector style="width:300px">#}
{#	        <span class=tag>#}
{#		    jQuery <a>×</a>#}
{#		   <input name=tags type=hidden value=42>#}
{#	       </span>#}
{#	       <input type=text>#}
{#        </div>#}



    <form method="post" id="aportacio">
        {% csrf_token %}
    <input id="url" name="url" type="hidden">
{#        <p>#}
{#        <label for="id_titol"></label>#}
{#        <input id="id_titol" type="text" name="titol" maxlength="40">#}
{#        </p>#}
{#        <p>#}
{#        <label for="id_entradilla">#}
{#        Entradilla:#}
{#        </label>#}
{#        <textarea id="id_entradilla" rows="10" name="entradilla" cols="40" class="entradeta"></textarea>#}
{#        </p>#}
{#        <div id="enlaces">#}
{#        <p>#}
{#        <label for="id_text">#}
{#        Text:#}
{#        </label>#}
{#        <textarea id="id_text" name="url" rows="10" cols="40" class="hidden_id"></textarea>#}
{#        </p>#}
{#        <div id="result1"></div>#}
{#        <div id="result2"></div>#}
{#        <div id="result3"></div>#}
{#        <div id="result4"></div>#}
{#        </div>#}
{#        <p>#}
{#        <label for="id_tags">#}
{#        Tags:#}
{#        </label>#}
{#        <input id="id_tags" class="autocomplete autocomplete-light-text-widget" type="text" placeholder="Type some text to search in this autocomplete" name="tags" maxlength="255" data-widget-bootstrap="text" data-autocomplete-url="/autocomplete/TagAutocomplete/" data-autocomplete-choice-selector="[data-value]" autocomplete="off" data-widget-ready="1"></input>#}
{#        </p>#}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                <p>
                {{ field.label }}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}</p>
                {% if field.name == 'text' %}
{#            <form id="form_links">#}
        <div id="result1"></div>
        <div id="result2"></div>
        <div id="result3"></div>
        <div id="result4"></div>

{#                    <input id="p_result1" type="hidden">#}
{#                    <input id="p_result1" type="hidden">#}
{#                    <input id="p_result1" type="hidden">#}
{#                    </form>#}
                {% endif %}
            {% endfor %}



        <input type="submit" value="OK">


    </form>



{% endblock %}

Xarxa/templates/Xarxa/aportacio_updateform.html
{% extends "base.html" %}

{% load micawber_tags %}
{% load tagging_tags %}


{#<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/themes/base/jquery-ui.css"#}
{#      rel=stylesheet type="text/css" xmlns="http://www.w3.org/1999/html">#}
{#    <link href="jquery-tagselector.css" rel=stylesheet>#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>#}
{#    <script src="jquery-tagselector.js"></script>#}

    <script>
    $(function() {

        var tags = [
            { id: 42, toString: function() { return 'jQuery'; } },
            { id: 31, toString: function() { return 'Python'; } },
            { id: 25, toString: function() { return 'HTML'; } },
            { id: 83, toString: function() { return 'PHP'; } },
            { id: 40, toString: function() { return 'ASP.NET MVC'; } },
            { id: 25, toString: function() { return 'CSS'; } },
            { id: 66, toString: function() { return 'JavaScript'; } },
            { id: 87, toString: function() { return 'C#'; } },
            { id: 28, toString: function() { return 'D'; } },
            { id: 91, toString: function() { return 'Java'; } },
            { id: 10, toString: function() { return 'Ruby'; } },
        ];
        $('#tags').tagSelector(tags, 'tags');

    });
    </script>




{% block content %}

{#        <div id=tags class=tagSelector style="width:300px">#}
{#	        <span class=tag>#}
{#		    jQuery <a>×</a>#}
{#		   <input name=tags type=hidden value=42>#}
{#	       </span>#}
{#	       <input type=text>#}
{#        </div>#}



    <form method="post" id="aportacio">
        {% csrf_token %}
    <input id="url" name="url" type="hidden">
{#        <p>#}
{#        <label for="id_titol"></label>#}
{#        <input id="id_titol" type="text" name="titol" maxlength="40">#}
{#        </p>#}
{#        <p>#}
{#        <label for="id_entradilla">#}
{#        Entradilla:#}
{#        </label>#}
{#        <textarea id="id_entradilla" rows="10" name="entradilla" cols="40" class="entradeta"></textarea>#}
{#        </p>#}
{#        <div id="enlaces">#}
{#        <p>#}
{#        <label for="id_text">#}
{#        Text:#}
{#        </label>#}
{#        <textarea id="id_text" name="url" rows="10" cols="40" class="hidden_id"></textarea>#}
{#        </p>#}
{#        <div id="result1"></div>#}
{#        <div id="result2"></div>#}
{#        <div id="result3"></div>#}
{#        <div id="result4"></div>#}
{#        </div>#}
{#        <p>#}
{#        <label for="id_tags">#}
{#        Tags:#}
{#        </label>#}
{#        <input id="id_tags" class="autocomplete autocomplete-light-text-widget" type="text" placeholder="Type some text to search in this autocomplete" name="tags" maxlength="255" data-widget-bootstrap="text" data-autocomplete-url="/autocomplete/TagAutocomplete/" data-autocomplete-choice-selector="[data-value]" autocomplete="off" data-widget-ready="1"></input>#}
{#        </p>#}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                <p>
                {{ field.label }}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}</p>
                {% if field.name == 'text' %}
{#            <form id="form_links">#}
                    <b>Enllaços:</b><br>
{% for link in object.links.get_query_set %}
    {{ link.url|oembed }} <br>
{% endfor %}
        <div id="result1"></div>
        <div id="result2"></div>
        <div id="result3"></div>
        <div id="result4"></div>

{#                    <input id="p_result1" type="hidden">#}
{#                    <input id="p_result1" type="hidden">#}
{#                    <input id="p_result1" type="hidden">#}
{#                    </form>#}
                {% endif %}
            {% endfor %}



        <input type="submit" value="OK">


    </form>



{% endblock %}

Xarxa/templates/Xarxa/debat_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>
        {#    <a href="{{ object.post }}"> #}
        Títol:    {{ object.titol }}

        {#</a>#}
    </h2>

    Entradeta: {{ object.entradilla }}<br>
    {% if object.autor == user %}
        <a class="button" href="{% url 'debat_update' object.id %}">MODIFICAR</a>
    {% endif %}
{% endblock %}

Xarxa/templates/Xarxa/debat_form.html
{% extends "base.html" %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}

        {#<input type="hidden" name="fornada" value={{ obj.pk }} />#}
        {#  <input type="text" id="datepicker" size="30">#}

        <input type="submit" value="OK">
    </form>
{% endblock %}

Xarxa/templates/Xarxa/debat_list.html
{% extends "base.html" %}

{% block content %}

        {% for thing in object_list %}
            {% for branch, obj in thing.as_tree %}
                {% if obj %}
                    {% if not obj.parent %}
{# Aqui posem el codi que es correspon amb el comentari que genera l'aportacio, recuperem els seus valors i tota la #}
{#  gestió dels vots en ajax seguin el model d'aportacio #}
                                <form method="post" action="{% url 'vote' %}" class="vote_form">
                                <li> [{{ ap_vots_total }}]
                                {% csrf_token %}
                                 <input type="hidden" id="id_aportacio" name="aportacio" class="hidden_id" value="{{ obj.aportacio.pk }}" />
                                 <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
                                 {% if not user.is_authenticated %}
                                    <button disabled title="Please login to vote">+</button>
                                 {% elif user.pk not in ap_voted_by %}
                                    <button>+</button>
                                 {% else %}
                                    <button>-</button>
                                 {% endif %}     <b>{{ obj.aportacio.titol }}</b>   {{ obj.aportacio.autor }}
                                    <div class="title"></div>

                                            {{ obj.aportacio.entradilla }}

                                        <div>
                                            <a class="button" href="{% url 'debat_create' obj.aportacio.id obj.id %}">Respondre | </a>
                                            <a class="button" href="{% url 'aportacio_detail' obj.aportacio.id %}">Detall | </a>
                                            {% if aportacio.autor == user %}
                                                <a class="button" href="{% url 'aportacio_update' obj.aportacio.id %}">Modificar | </a>
                                            {% endif %}
                                            <a class="button">[{{ obj.aportacio.debats.count }}]Comentaris | Comparteix |</a>
                                        </div>
                                </li>
                                </form>

                    {% elif obj.parent %}

                    <form method="post" action="{% url 'votedebat' %}" class="votedebat_form">
                    <li>[{{ obj.votes }}]
                        {% csrf_token %}
                         <input type="hidden" id="id_debat" name="debat" class="hidden_id" value="{{ obj.pk }}" />
                         <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
                         {% if not user.is_authenticated %}
                            <button disabled title="Please login to vote">+</button>
                         {% elif obj.pk not in voted %}
                            <button>+</button>
                         {% else %}
                            <button>-</button>
                         {% endif %}<b>{{ obj.titol }}</b>  {{ obj.autor }}
                            <div class="title"></div>
                                    {{ obj.text }}
                            <div>
                                    {% if obj.autor == user %}
                                     <a class="button" href="{% url 'debat_update' obj.id %}">Modificar</a>
                                    {% endif %}
                                     <a class="button" href="{% url 'debat_create' obj.aportacio.id obj.id %}">Respon</a>
                            </div>
                    {% endif %}
                            {% if branch %}
                                <ul>
                            {% else %}
                                </li>
                            {% endif %}
                    {% else %}
                        {% if branch %}
                                </ul>
                        {% endif %}
                    {% endif %}
                </form>
            {% endfor %}
        {% endfor %}
{% endblock %}

Xarxa/templates/Xarxa/escritori_list.html
{% extends "base.html" %}

{% block content %}
    <p>Estas al Escritori</p>
    <p>En el mundo hay...</p>
{% endblock %}

Xarxa/templates/Xarxa/resum_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>
        {#    <a href="{{ object.post }}"> #}
        Títol:    {{ object.titol }}

        {#</a>#}
    </h2>


    <a class="button" href="{% url 'resum_update' object.id %}">MODIFICAR</a>

{% endblock %}

Xarxa/templates/Xarxa/resum_form.html
{% extends "base.html" %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}

        {#<input type="hidden" name="fornada" value={{ obj.pk }} />#}
        {#  <input type="text" id="datepicker" size="30">#}

        <input type="submit" value="OK">
    </form>
{% endblock %}